[tool.black]
line-length = 119
target-version = ['py37']

[tool.isort]
profile = "black"
multi_line_output = 3
py_version = "37"

[tool.pyright]
pythonVersion = "3.7"

[tool.pytest.ini_options]
asyncio_mode = "auto"
