name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v3

    - name: Install
      run: |
        sudo apt-get update
        sudo apt-get install pandoc python3-pytest
        python3 -m pip install --upgrade setuptools wheel pip
        python3 -m pip install mypy ruff
        npm install -g pyright

    - name: Run ruff
      run: |
        ruff --version
        ruff mkosi/ tests/ kernel-install/50-mkosi.install

    - name: Check that tabs are not used in code
      run: sh -c '! git grep -P "\\t" "*.py"'

    - name: Type Checking (mypy)
      run: |
        python3 -m mypy --version
        python3 -m mypy mkosi/ tests/ kernel-install/50-mkosi.install

    - name: Type Checking (pyright)
      run: |
        pyright --version
        pyright mkosi/ tests/ kernel-install/50-mkosi.install

    - name: Unit Tests
      run: |
        python3 -m pytest --version
        python3 -m pytest -sv tests/

    - name: Test execution from current working directory
      run: python3 -m mkosi -h

    - name: Test execution from current working directory (sudo call)
      run: sudo python3 -m mkosi -h

    - name: Test venv installation
      run: |
        python3 -m venv testvenv
        testvenv/bin/python3 -m pip install --upgrade setuptools wheel pip
        testvenv/bin/python3 -m pip install .
        testvenv/bin/mkosi -h
        rm -rf testvenv

    - name: Test editable venv installation
      run: |
        python3 -m venv testvenv
        testvenv/bin/python3 -m pip install --upgrade setuptools wheel pip
        testvenv/bin/python3 -m pip install --editable .
        testvenv/bin/mkosi -h
        rm -rf testvenv

    - name: Test zipapp creation
      run: |
        ./tools/generate-zipapp.sh
        ./builddir/mkosi -h

    - name: Test shell scripts
      run: |
        sudo apt-get update && sudo apt-get install --no-install-recommends shellcheck
        bash -c 'shopt -s globstar; shellcheck bin/mkosi tools/*.sh'

    - name: Test man page generation
      run: pandoc -s mkosi.md -o mkosi.1

  integration-test:
    runs-on: ubuntu-22.04
    needs: unit-test
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.distro }}-${{ matrix.format }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        distro:
          - arch
          - centos
          - rhel-ubi
          - debian
          - ubuntu
          - fedora
          - rocky
          - alma
          - opensuse

    steps:
    - uses: actions/checkout@v3
    - uses: ./

    - name: Install
      run: |
        sudo apt-get update
        sudo apt-get install python3-pytest lvm2 cryptsetup-bin
        # Make sure the latest changes from the pull request are used.
        sudo ln -svf $PWD/bin/mkosi /usr/bin/mkosi
      working-directory: ./

    - name: Configure
      run: |
        tee mkosi.local.conf <<EOF
        [Content]
        KernelCommandLine=systemd.default_device_timeout_sec=180

        [Host]
        QemuKvm=no
        EOF

        # TODO: Remove once all distros have recent enough systemd that knows systemd.default_device_timeout_sec.
        mkdir -p mkosi-initrd/mkosi.extra/usr/lib/systemd/system.conf.d
        tee mkosi-initrd/mkosi.extra/usr/lib/systemd/system.conf.d/device-timeout.conf <<EOF
        [Manager]
        DefaultDeviceTimeoutSec=180
        EOF

    - name: Run integration tests
      run: sudo --preserve-env timeout -k 30 1h python3 -m pytest --tb=no -sv -m integration -D ${{ matrix.distro }} tests/
